server:
  port: 8761

spring:
  profiles: docker
  cloud:
    config:
      uri: http://config:8888
      retry:
        max-attempts: 5
        initial-interval: 2000

management:
  endpoints:
    web:
      exposure:
        include: '*'