server:
  port: 8761

spring:
  profiles:
    active: docker 
  cloud:
    config:
      uri: http://config:8888
      retry:
        max-attempts: 5
        initial-interval: 2000

eureka:
  client:
    register-with-eureka: false  
    fetch-registry: false 
  server:
    wait-time-in-ms-when-sync-empty: 0
    enableSelfPreservation: false

management:
  endpoints:
    web:
      exposure:
        include: '*'